name: RetainIQ CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci-build-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker Compose services
        run: docker compose build

      - name: Start services
        run: docker compose up -d

      - name: Check running containers
        run: docker ps

      - name: Stop services
        run: docker compose down